insert into sexo(sexo) values('Masculino');
insert into sexo(sexo) values('Femenino');
insert into estado(nombre) values('Aguascalientes');
insert into estado(nombre) values('Baja California');
insert into estado(nombre) values('Baja California Sur');
insert into estado(nombre) values('Campeche');
insert into estado(nombre) values('Chiapas');
insert into estado(nombre) values('Chihuahua');
insert into estado(nombre) values('Ciudad de Mexico');
insert into estado(nombre) values('Coahuila de Zaragoza');
insert into estado(nombre) values('Colima');
insert into estado(nombre) values('Durango');
insert into estado(nombre) values('Guanajuato');
insert into estado(nombre) values('Guerrero');
insert into estado(nombre) values('Hidalgo');
insert into estado(nombre) values('Jalisco');
insert into estado(nombre) values('Mexico');
insert into estado(nombre) values('Michoacan de Ocampo');
insert into estado(nombre) values('Morelos');
insert into estado(nombre) values('Nayarit');
insert into estado(nombre) values('Nuevo Leon');
insert into estado(nombre) values('Oaxaca');
insert into estado(nombre) values('Puebla');
insert into estado(nombre) values('Queretaro Arteaga');
insert into estado(nombre) values('Quintana Roo');
insert into estado(nombre) values('San Luis Potosi');
insert into estado(nombre) values('Sinaloa');
insert into estado(nombre) values('Sonora');
insert into estado(nombre) values('Tabasco');
insert into estado(nombre) values('Tamaulipas');
insert into estado(nombre) values('Tlaxcala');
insert into estado(nombre) values('Veracruz');
insert into estado(nombre) values('Yucatán');
insert into estado(nombre) values('Zacatecas');
insert into ciudad (nombre,idestado) values ('Aguascalientes',1);
insert into ciudad (nombre,idestado) values ('Mexicali',2);
insert into ciudad (nombre,idestado) values ('La Paz',3);
insert into ciudad (nombre,idestado) values ('Campeche',4);
insert into ciudad (nombre,idestado) values ('Tuxtla Gutierrez',5);
insert into ciudad (nombre,idestado) values ('Chihuahua',6);
insert into ciudad (nombre,idestado) values ('Ciudad de Mexico',7);
insert into ciudad (nombre,idestado) values ('Saltillo',8);
insert into ciudad (nombre,idestado) values ('Colima',9);
insert into ciudad (nombre,idestado) values ('Victoria de Durango',10);
insert into ciudad (nombre,idestado) values ('Guanajuato',11);
insert into ciudad (nombre,idestado) values ('Chilpancingo de los Bravo',12);
insert into ciudad (nombre,idestado) values ('Pachuca de Soto',13);
insert into ciudad (nombre,idestado) values ('Guadalajara',14);
insert into ciudad (nombre,idestado) values ('Toluca de Lerdo',15);
insert into ciudad (nombre,idestado) values ('Morelia',16);
insert into ciudad (nombre,idestado) values ('Cuernavaca',17);
insert into ciudad (nombre,idestado) values ('Tepic',18);
insert into ciudad (nombre,idestado) values ('Monterrey',19);
insert into ciudad (nombre,idestado) values ('Oaxaca de Juarez',20);
insert into ciudad (nombre,idestado) values ('H. Puebla de Zaragoza',21);
insert into ciudad (nombre,idestado) values ('Santiago de Queretaro',22);
insert into ciudad (nombre,idestado) values ('Cd. Chetumal',23);
insert into ciudad (nombre,idestado) values ('San Luis Potosi',24);
insert into ciudad (nombre,idestado) values ('Culiacan Rosales',25);
insert into ciudad (nombre,idestado) values ('Hermosillo',26);
insert into ciudad (nombre,idestado) values ('Villahermosa',27);
insert into ciudad (nombre,idestado) values ('Ciudad Victoria',28);
insert into ciudad (nombre,idestado) values ('Tlaxcala de Xicohtencatl',29);
insert into ciudad (nombre,idestado) values ('Xalapa de Enriquez',30);
insert into ciudad (nombre,idestado) values ('Merida',31);
insert into ciudad (nombre,idestado) values ('Zacatecas',32);

insert into nombre(nombre,appat,apmat) values ();