insert into sexo(sexo) values('Masculino');
insert into sexo(sexo) values('Femenino');
insert into sexo(sexo) values('Masculino');
insert into sexo(sexo) values('Femenino');
insert into estado(nombre) values('Aguascalientes');
insert into estado(nombre) values('Baja California');
insert into estado(nombre) values('Baja California Sur');
insert into estado(nombre) values('Campeche');
insert into estado(nombre) values('Chiapas');
insert into estado(nombre) values('Chihuahua');
insert into estado(nombre) values('Ciudad de Mexico');
insert into estado(nombre) values('Coahuila de Zaragoza');
insert into estado(nombre) values('Colima');
insert into estado(nombre) values('Durango');
insert into estado(nombre) values('Guanajuato');
insert into estado(nombre) values('Guerrero');
insert into estado(nombre) values('Hidalgo');
insert into estado(nombre) values('Jalisco');
insert into estado(nombre) values('Mexico');
insert into estado(nombre) values('Michoacan de Ocampo');
insert into estado(nombre) values('Morelos');
insert into estado(nombre) values('Nayarit');
insert into estado(nombre) values('Nuevo Leon');
insert into estado(nombre) values('Oaxaca');
insert into estado(nombre) values('Puebla');
insert into estado(nombre) values('Queretaro Arteaga');
insert into estado(nombre) values('Quintana Roo');
insert into estado(nombre) values('San Luis Potosi');
insert into estado(nombre) values('Sinaloa');
insert into estado(nombre) values('Sonora');
insert into estado(nombre) values('Tabasco');
insert into estado(nombre) values('Tamaulipas');
insert into estado(nombre) values('Tlaxcala');
insert into estado(nombre) values('Veracruz');
insert into estado(nombre) values('Yucatán');
insert into estado(nombre) values('Zacatecas');
insert into ciudad (nombre,idestado) values ('Aguascalientes',1);
insert into ciudad (nombre,idestado) values ('Mexicali',2);
insert into ciudad (nombre,idestado) values ('La Paz',3);
insert into ciudad (nombre,idestado) values ('Campeche',4);
insert into ciudad (nombre,idestado) values ('Tuxtla Gutierrez',5);
insert into ciudad (nombre,idestado) values ('Chihuahua',6);
insert into ciudad (nombre,idestado) values ('Ciudad de Mexico',7);
insert into ciudad (nombre,idestado) values ('Saltillo',8);
insert into ciudad (nombre,idestado) values ('Colima',9);
insert into ciudad (nombre,idestado) values ('Victoria de Durango',10);
insert into ciudad (nombre,idestado) values ('Guanajuato',11);
insert into ciudad (nombre,idestado) values ('Chilpancingo de los Bravo',12);
insert into ciudad (nombre,idestado) values ('Pachuca de Soto',13);
insert into ciudad (nombre,idestado) values ('Guadalajara',14);
insert into ciudad (nombre,idestado) values ('Toluca de Lerdo',15);
insert into ciudad (nombre,idestado) values ('Morelia',16);
insert into ciudad (nombre,idestado) values ('Cuernavaca',17);
insert into ciudad (nombre,idestado) values ('Tepic',18);
insert into ciudad (nombre,idestado) values ('Monterrey',19);
insert into ciudad (nombre,idestado) values ('Oaxaca de Juarez',20);
insert into ciudad (nombre,idestado) values ('H. Puebla de Zaragoza',21);
insert into ciudad (nombre,idestado) values ('Santiago de Queretaro',22);
insert into ciudad (nombre,idestado) values ('Cd. Chetumal',23);
insert into ciudad (nombre,idestado) values ('San Luis Potosi',24);
insert into ciudad (nombre,idestado) values ('Culiacan Rosales',25);
insert into ciudad (nombre,idestado) values ('Hermosillo',26);
insert into ciudad (nombre,idestado) values ('Villahermosa',27);
insert into ciudad (nombre,idestado) values ('Ciudad Victoria',28);
insert into ciudad (nombre,idestado) values ('Tlaxcala de Xicohtencatl',29);
insert into ciudad (nombre,idestado) values ('Xalapa de Enriquez',30);
insert into ciudad (nombre,idestado) values ('Merida',31);
insert into ciudad (nombre,idestado) values ('Zacatecas',32);
insert into nombre(nombre,appat,apmat) values ('Isarel','Limones','Vieyra');
insert into nombre(nombre,appat,apmat) values ('Samuel','Limones','Vieyra');
insert into nombre(nombre,appat,apmat) values ('Emmanuel','Limones','Vieyra');
insert into nombre(nombre,appat,apmat) values ('Isarel','Limones','Vieyra');
insert into nombre(nombre,appat,apmat) values ('Samuel','Limones','Vieyra');
insert into nombre(nombre,appat,apmat) values ('Emmanuel','Limones','Vieyra');
insert into colonia(nombre,codigopostal,idciudad) values('Las Brisas',20010,1);
insert into colonia(nombre,codigopostal,idciudad) values('Nueva Esperanza',21050,2);
insert into colonia(nombre,codigopostal,idciudad) values('Lomas de Palmira',23010,3);
insert into colonia(nombre,codigopostal,idciudad) values('San Joaquín',24020,4);
insert into colonia(nombre,codigopostal,idciudad) values('Rosario Poniente',29014,5);
insert into colonia(nombre,codigopostal,idciudad) values('Cuarteles',31020,6);
insert into colonia(nombre,codigopostal,idciudad) values('Atlántida',04370,7);
insert into colonia(nombre,codigopostal,idciudad) values('Loma Linda',25016,8);
insert into colonia(nombre,codigopostal,idciudad) values('Las Palmas',28017,9);
insert into colonia(nombre,codigopostal,idciudad) values('Revolución',34892,10);
insert into colonia(nombre,codigopostal,idciudad) values('La Bufa',36094,11);
insert into colonia(nombre,codigopostal,idciudad) values('Azteca',39010,12);
insert into colonia(nombre,codigopostal,idciudad) values('Los Cedros',42033,13);
insert into colonia(nombre,codigopostal,idciudad) values('El Jaguey',44249,14);
insert into colonia(nombre,codigopostal,idciudad) values('San Juanito',56120,15);
insert into colonia(nombre,codigopostal,idciudad) values('Cosmos',58050,16);
insert into colonia(nombre,codigopostal,idciudad) values('El Veladero',62243,17);
insert into colonia(nombre,codigopostal,idciudad) values('Reforma',63038,18);
insert into colonia(nombre,codigopostal,idciudad) values('Real Cumbres',64346,19);
insert into colonia(nombre,codigopostal,idciudad) values('Revolución',68010,20);
insert into colonia(nombre,codigopostal,idciudad) values('Polideportivo',72014,21);
insert into colonia(nombre,codigopostal,idciudad) values('Diligencias',76020,22);
insert into colonia(nombre,codigopostal,idciudad) values('Maya Pax',77760,23);
insert into colonia(nombre,codigopostal,idciudad) values('La Matamoros',78100,24);
insert into colonia(nombre,codigopostal,idciudad) values('El Caiman',81902,25);
insert into colonia(nombre,codigopostal,idciudad) values('El Alamito',84640,26);
insert into colonia(nombre,codigopostal,idciudad) values('El Parnaso',86495,27);
insert into colonia(nombre,codigopostal,idciudad) values('Bellavista',88179,28);
insert into colonia(nombre,codigopostal,idciudad) values('Los Volcanes',90014,29);
insert into colonia(nombre,codigopostal,idciudad) values('Solidaridad',91013,30);
insert into colonia(nombre,codigopostal,idciudad) values('Itzimna',97100,31);
insert into colonia(nombre,codigopostal,idciudad) values('De Olivos',98024,32);

update ciudad set nombre='Coyoacan' where idciudad=7;
update ciudad set nombre='Vicente Guerrero' where idciudad=11;
update ciudad set nombre='Texcoco' where idciudad=15;
update ciudad set nombre='Puebla' where idciudad=21;
update ciudad set nombre='Xalapa' where idciudad=30;

delete sexo where idsexo=1002;
delete sexo where idsexo=1003;
delete nombre where idnombre=1003;
delete nombre where idnombre=1004;
delete nombre where idnombre=1005;